---
title: "Mortality Validation Code"
author: Casey Breen and Maria Osborne 
---

Summary: This script generates Figure 1, which compares the age-specific mortality rates for CenSoc-DMF and CenSoc-Numident to the "gold-standard" Human Mortality Database (HMD). 


```{r}
## Library packages 
library(tidyverse)
library(data.table)
library(here)
library(cowplot)
library(broom)

## read in data 
numident <- fread("/data/censoc/censoc_data_releases/censoc_numident/censoc_numident_v3/censoc_numident_v3.csv")
dmf <- fread("/data/censoc/censoc_data_releases/censoc_dmf/censoc_dmf_v3/censoc_dmf_v3.csv")

hmd_mr <- fread(here("data/USA.cMx_1x1.txt"))
hmd_exposure <- fread(here("data/USA.cExposures_1x1.txt"))
```


## Calculate hmd mortality rates 

```{r}
## hmd mortality rates  
hmd_cohort_1910 <- hmd_mr %>% 
  filter(Year == 1910)  %>% 
  filter(Age %in% 50:95) %>% 
  mutate(age = as.numeric(Age),
         female = as.numeric(Female),
         male = as.numeric(Male),
         total = as.numeric(Total)) %>% 
  mutate(source = "HMD (Human Mortality Database)") %>% 
  mutate(death_age = age) 
```


## calculate adjustment factors for censoc deaths past highest observed age

```{r}
## calculate adjustment factor for deaths after age 94 (numident) 
l_78 <- as.numeric(hmd_exposure[Year == 1910][Age == 78]$Male)
l_95 <- as.numeric(hmd_exposure[Year == 1910][Age == 95]$Male)
numident_adjustment <- (l_78 + l_95)/l_78

## calculate adjustment factor for deaths occuring after age 94 (dmf)
l_65 <- as.numeric(hmd_exposure[Year == 1910][Age == 65]$Male)
l_95 <- as.numeric(hmd_exposure[Year == 1910][Age == 95]$Male)
dmf_adjustment <- (l_65 + l_95)/l_65
```



## calculate numident mortality rates 

```{r}
## numident mortality rates 
numident <- numident %>% 
  filter(byear == 1910)

## numident mortality rate (adjusted)
numident_mr_adjusted <- numident %>% 
  filter(death_age != min(death_age) & death_age != max(death_age)) %>% 
  group_by(sex, death_age) %>% 
  summarize(n = sum(weight)) %>% 
  mutate(total_deaths = sum(n) * numident_adjustment) %>% ## estimated from hmd exposure 
  mutate(cum_deaths = cumsum(n)) %>% 
  mutate(survivors = total_deaths - lag(cum_deaths)) %>% 
  mutate(male = n / survivors) %>% 
  dplyr::select(death_age, male) %>% 
  mutate(source = "CenSoc-Numident Reverse Survival (Adjusted)") %>% 
  filter(sex == 1)

## numident mortality rate (unadjusted)
numident_mr <- numident %>% 
  filter(death_age != min(death_age) & death_age != max(death_age)) %>% 
  group_by(sex, death_age) %>% 
  summarize(n = sum(weight)) %>% 
  mutate(total_deaths = sum(n)) %>% 
  mutate(cum_deaths = cumsum(n)) %>% 
  mutate(survivors = total_deaths - lag(cum_deaths)) %>% 
  mutate(male = n / survivors) %>% 
  dplyr::select(death_age, male) %>% 
  mutate(source = "CenSoc-Numident Reverse Survival") %>% 
  filter(sex == 1)

## numident mortality rate validation plot 
numident_mortality_validation <- numident_mr_adjusted  %>% 
  bind_rows(hmd_cohort_1910) %>% 
  ggplot(aes(x = death_age, y = male, color = source, linetype = source)) + 
  geom_line(size = 1.5, alpha = 1) + 
  # ggsci::scale_color_lancet() + 
  scale_color_manual(values=c("blue", "black")) + 
  scale_linetype_manual(values=c("dashed", "solid")) + 
  scale_y_continuous(trans='log10') + 
  cowplot::theme_cowplot() + 
  theme(legend.position = "bottom",
        legend.key.width=unit(3, "cm"),
        legend.title=element_blank()) + 
  xlim(65, 100) + 
  labs(x = "Death Age",
       y = "Mortality Rate",
       title = "CenSoc-Numident 1910 Cohort") + 
  guides(color = guide_legend(nrow = 3))
```

## calculate dmf mortality rates 

```{r}
## dmf filter to 1910
dmf <- dmf %>% 
  filter(byear == 1910) 

## dmf mortality rate (adjusted)
dmf_mr_adjusted <- dmf %>% 
  filter(death_age != min(death_age) & death_age != max(death_age)) %>% 
  group_by(death_age) %>% 
  summarize(n = sum(weight)) %>% 
  mutate(total_deaths = sum(n)  * dmf_adjustment) %>% 
  mutate(cum_deaths = cumsum(n)) %>% 
  mutate(survivors = total_deaths - lag(cum_deaths)) %>% 
  mutate(male = n / survivors) %>% 
  dplyr::select(death_age, male) %>% 
  mutate(source = "CenSoc-DMF Reverse Survival (Adjusted)")

## dmf mortality rate (unadjusted)
# dmf_mr <- dmf %>% 
#   filter(death_age != min(death_age) & death_age != max(death_age)) %>% 
#   group_by(death_age) %>% 
#   summarize(n = sum(weight_final)) %>% 
#   mutate(total_deaths = sum(n)) %>% ## estimated from hmd exposure 
#   mutate(cum_deaths = cumsum(n)) %>% 
#   mutate(survivors = total_deaths - lag(cum_deaths)) %>% 
#   mutate(male = n / survivors) %>% 
#   dplyr::select(death_age, male) %>% 
#   mutate(source = "CenSoc-DMF Reverse Survival")

## dmf mortality rate validation plot 
dmf_mortality_estimation <- hmd_cohort_1910 %>% 
  mutate(death_age = age) %>% 
  bind_rows(dmf_mr_adjusted) %>% 
  ggplot(aes(x = death_age, y = male, color = source, linetype = source)) + 
  geom_line(size = 1.5, alpha = 1) + 
  scale_color_manual(values=c("blue", "black")) + 
  scale_linetype_manual(values=c("dashed", "solid")) + 
  scale_y_continuous(trans='log10') + 
  cowplot::theme_cowplot() + 
    theme(legend.position = "bottom",
          legend.key.width=unit(3, "cm"),
          legend.title=element_blank()) + 
  xlim(65, 100) + 
  labs(x = "Death Age",
       y = "Mortality Rate",
       title = "CenSoc-DMF 1910 Cohort") + 
  guides(color = guide_legend(nrow = 3)) 
```


```{r}
## combined mortality validation plot
validation_mortality_plot <- cowplot::plot_grid(numident_mortality_validation, dmf_mortality_estimation, labels = "auto")

## save combined mortality estimation plot 
ggsave(validation_mortality_plot, filename = here("figs/fig1_mortality_validation_hmd_plot.png"), width = 12, height = 5)
```


