---
title: "Mortality Validation Code"
author: Casey Breen
---

Mortality validation Code

```{r}
## Library packages 
library(tidyverse)
library(data.table)
library(memisc)
library(here)
library(HMDHFDplus)
library(gridExtra)
library(ggpubr)
library(cowplot)
library(gt)
library(fixest)
library(stargazer)
library(choroplethrZip)
library(choroplethr)
library(sf)
library(ggplot2)
library(broom)
library(lubridate)
library(censocdev)
library(ggrepel)

## read in data 
numident <- fread("/censoc/data/censoc_v2.1/censoc_numident_v2.1.csv") %>% filter(link_abe_exact_conservative == 1)
dmf <- fread("/censoc/data/censoc_v2.1/censoc_dmf_v2.1.csv")  %>% filter(link_abe_exact_conservative == 1)

hmd_mr <- fread("/data/josh/CenSoc/hmd/hmd_statistics/c_death_rates/cMx_1x1/USA.cMx_1x1.txt") 
hmd_exposure <- fread("/data/josh/CenSoc/hmd/hmd_statistics/c_exposures/cExposures_1x1/USA.cExposures_1x1.txt")
```


```{r}
## hmd mortality rates  
hmd_cohort_1910 <- hmd_mr %>% 
  filter(Year == 1910)  %>% 
  filter(Age %in% 50:95) %>% 
  mutate(age = as.numeric(Age),
         female = as.numeric(Female),
         male = as.numeric(Male),
         total = as.numeric(Total)) %>% 
  mutate(source = "HMD (Human Mortality Database)")
```


```{r}
## numident mortality rates 
numident <- numident %>% 
  filter(byear == 1910)

## numident mortality rate 
numident_mr <- numident %>% 
  filter(death_age != min(death_age) & death_age != max(death_age)) %>% 
  group_by(sex, death_age) %>% 
  summarize(n = sum(weight_conservative)) %>% 
  mutate(total_deaths = sum(n) * 1.05352238) %>% 
  mutate(cum_deaths = cumsum(n)) %>% 
  mutate(survivors = total_deaths - lag(cum_deaths)) %>% 
  mutate(male = n / survivors) %>% 
  dplyr::select(death_age, male) %>% 
  mutate(source = "CenSoc-Numident Reverse Survival (Adjusted)")

## numident mortality rate adjusted 
numident_mr_adjusted <- numident %>% 
  filter(death_age != min(death_age) & death_age != max(death_age)) %>% 
  group_by(sex, death_age) %>% 
  summarize(n = sum(weight_conservative)) %>% 
  mutate(total_deaths = sum(n)) %>% 
  mutate(cum_deaths = cumsum(n)) %>% 
  mutate(survivors = total_deaths - lag(cum_deaths)) %>% 
  mutate(male = n / survivors) %>% 
  dplyr::select(death_age, male) %>% 
  mutate(source = "CenSoc-Numident Reverse Survival")

## numident mortality rate validation plot 
numident_mortality_validation <- hmd_cohort_1910 %>% 
  mutate(death_age = age) %>% 
  bind_rows(numident_mort_weight %>% 
              filter(sex == 1)) %>% 
   bind_rows(numident_mort %>% 
              filter(sex == 1)) %>% 
  ggplot(aes(x = death_age, y = male, color = source, linetype = source)) + 
  geom_line(size = 1.5, alpha = 0.9) + 
  # ggsci::scale_color_lancet() + 
  scale_color_manual(values=c("red", "blue", "black")) + 
  scale_linetype_manual(values=c("solid", "solid", "dashed")) + 
  scale_y_continuous(trans='log10') + 
  cowplot::theme_cowplot() + 
  theme(legend.position = "bottom",
        legend.key.width=unit(3, "cm"),
        legend.title=element_blank()) + 
  xlim(65, 100) + 
  labs(x = "Death Age",
       y = "Mortality Rate",
       title = "CenSoc-Numident Mortality Rates (Cohort 1910)") + 
  guides(color = guide_legend(nrow = 3))
```


```{r}
## dmf filter to 1910
dmf <- dmf %>% 
  filter(byear == 1910) 

## dmf mortality rate 
dmf_mort_weight <- dmf %>% 
  filter(death_age != min(death_age) & death_age != max(death_age)) %>% 
  group_by(death_age) %>% 
  summarize(n = sum(weight_conservative)) %>% 
  mutate(total_deaths = sum(n)) %>% 
  mutate(cum_deaths = cumsum(n)) %>% 
  mutate(survivors = total_deaths - lag(cum_deaths)) %>% 
  mutate(male = n / survivors) %>% 
  dplyr::select(death_age, male) %>% 
  mutate(source = "CenSoc-DMF Reverse Survival")

## dmf mortality rate adjusted
dmf_mort <- dmf %>% 
  filter(death_age != min(death_age) & death_age != max(death_age)) %>% 
  group_by(death_age) %>% 
  summarize(n = sum(weight_conservative)) %>% 
  mutate(total_deaths = sum(n) * 1.02705555) %>% 
  mutate(cum_deaths = cumsum(n)) %>% 
  mutate(survivors = total_deaths - lag(cum_deaths)) %>% 
  mutate(male = n / survivors) %>% 
  dplyr::select(death_age, male) %>% 
  mutate(source = "CenSoc-DMF Reverse Survival (Adjusted)")

## dmf mortality rate validation plot 
dmf_mortality_estimation <- hmd_cohort_1910 %>% 
  mutate(death_age = age) %>% 
  bind_rows(dmf_mort_weight) %>% 
   bind_rows(dmf_mort) %>% 
  ggplot(aes(x = death_age, y = male, color = source, linetype = source)) + 
  geom_line(size = 1.5, alpha = .9) + 
  scale_color_manual(values=c("red", "blue", "black")) + 
  scale_linetype_manual(values=c("solid", "solid", "dashed")) + 
  scale_y_continuous(trans='log10') + 
  cowplot::theme_cowplot() + 
    theme(legend.position = "bottom",
          legend.key.width=unit(3, "cm"),
          legend.title=element_blank()) + 
  xlim(65, 100) + 
  labs(x = "Death Age",
       y = "Mortality Rate",
       title = "CenSoc-DMF Mortality Rates (Cohort 1910)") + 
  guides(color = guide_legend(nrow = 3)) 
```


```{r}
## combined mortality validation plot
validation_mortality_plot <- cowplot::plot_grid(numident_mortality_validation, dmf_mortality_estimation, labels = "auto")

## save combined mortality estimation plot 
ggsave(validation_mortality_plot, filename = "figs/mortality_validation_hmd_plot.png", width = 14, height = 6)
```



